Repository ClarkeWilliford/ShopProjectApp, pull requests merged in 2022-04, with the labels that each got.

#8 Added DBHelper functions.
  Model/DBHelper.swift
  Model/Items.swift
  ShopProjectApp.xcodeproj/project.pbxproj
Labels: Design, Build

#16 cart mostly finished.
  ShopProjectApp/AppDelegate.swift
  ShopProjectApp/Controllers/CartViewController.swift
  ShopProjectApp/Controllers/ProceedToCheckoutTableViewCell.swift
  ShopProjectApp/Controllers/ProceedToCheckoutTableViewCell.xib
  ShopProjectApp/Controllers/PurchasedItemTableViewCell.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: Design, Build

#18 created the displayItemView to show the currently chosen item and giv…
  ShopProjectApp.xcodeproj/project.pbxproj
  ShopProjectApp.xcodeproj/project.xcworkspace/xcuserdata/clarkewilliford.xcuserdatad/UserInterfaceState.xcuserstate
  ShopProjectApp/Controllers/SuggestedItemCollectionViewCell.swift
  ShopProjectApp/Controllers/displayItemViewController.swift
  ShopProjectApp/Model/DBHelper.swift
  ShopProjectApp/Model/GlobalVariables.swift
  ShopProjectApp/ShopGroupAppDB.db
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: Design, Build

#22 tabor functionality on all current pages in main
  ShopProjectApp.xcodeproj/project.pbxproj
  ShopProjectApp/Controllers/SearchBarViewController.swift
  ShopProjectApp/Controllers/TabBarViewController.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: Build

#28 Main copy 2
  .DS_Store
  ShopProjectApp/Controllers/ViewController.swift
  ShopProjectApp/Model/DataFetcher.swift
Labels: bug

#35 Main copy 3
  .DS_Store
  ShopProjectApp.xcodeproj/project.pbxproj
  ShopProjectApp/Controllers/CartViewController.swift
  ShopProjectApp/Controllers/CollectionTableViewCell.swift
  ShopProjectApp/Controllers/DealOfTheDayTableViewCell.swift
  ShopProjectApp/Controllers/ExampleTableViewCell.swift
  ShopProjectApp/Controllers/PlaceOrderViewController.swift
  ShopProjectApp/Controllers/ProceedToCheckoutTableViewCell.swift
  ShopProjectApp/Controllers/PurchasedItemTableViewCell.swift
  ShopProjectApp/Controllers/ViewController.swift
  ShopProjectApp/Controllers/displayItemViewController.swift
  ShopProjectApp/Model/DataFetcher.swift
  ShopProjectApp/Model/GlobalVariables.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
  ShopProjectApp/Views/DealOfTheDayTableViewCell.xib
  ShopProjectApp/Views/ExampleTableViewCell.xib
Labels: Build

#43 added search bar functionality to home page. needs to be updated beca…
  ShopProjectApp.xcodeproj/project.pbxproj
  ShopProjectApp/Controllers/SearchBarViewController.swift
  ShopProjectApp/Controllers/SearchContentViewController.swift
  ShopProjectApp/Controllers/ViewController.swift
  ShopProjectApp/Model/GlobalVariables.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: Build

#45 Main copy 2
  ShopProjectApp.xcodeproj/project.pbxproj
  ShopProjectApp/Controllers/SearchBarViewController.swift
  ShopProjectApp/Controllers/SearchContentViewController.swift
  ShopProjectApp/Controllers/TabBarViewController.swift
  ShopProjectApp/Controllers/ViewController.swift
  ShopProjectApp/Controllers/displayItemViewController.swift
  ShopProjectApp/Model/DBHelper.swift
  ShopProjectApp/Model/GlobalVariables.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: Build, Test

#46 fixed the merge conflict. it was a scene error in main xml file
  ShopProjectApp/Controllers/ViewController.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: Build, Test

#51 fixed not connected net bank button
  ShopProjectApp/Controllers/CartViewController.swift
  ShopProjectApp/Controllers/PlaceOrderViewController.swift
  ShopProjectApp/Views/Base.lproj/Main.storyboard
Labels: bug
